source/index.htm.erb

Commented out the old block of intro text and added the new block. 
New text found:
https://github.com/gridcoin-community/Gridcoin-Site/issues/25

Updated Index Page Copy

---

data/blog.yml
data/whitelist.yml

I added v3.7.4.0 to the blog and updated the whitelist to show the project ODLK1.

added v3.7.4.0 and ODLK1

---

source/Guides/gridcoin-install.htm.erb

Change the Guide for Ubuntu from daemon to GUI.
New User need normaly the GUI

Change the Guide for Ubuntu from daemon to GUI.

---

source/Guides/investor-gridcoin-setup.htm.erb
source/Guides/pool-gridcoin-install.htm.erb

Guide daemon gui

---

data/blog.yml
source/index.htm.erb

Added "Current Wallet Version: 3.7.11.0 to homepage, using the green hover color from the whitelist page.
Updated the blog with wallet version 3.7.11.0.

Added current wallet version to index, updated blog

---

source/layouts/partials/_footer.erb
source/layouts/partials/_header.erb

Added to header:
https://gridcoin.network/
https://grcexplorer.neuralminer.io/
Added to footer:
https://chat.gridcoin.io/
#84 
#69

Add Block Explorers to Header/Rocket to Footer

---

source/layouts/partials/_boinc_1B.erb

The image linked previously is no available on the server. I think this should be the correct path.

Changed the src of the bam logo

---

source/Guides/misc.htm.erb
source/contact.htm.erb
source/layouts/partials/_acquire_details.erb

Reverts gridcoin-community/Gridcoin-Site#124

Updated a bunch of URLs, dead links and grammar. #2

---

Old Data/social_media.erb
source/layouts/partials/_footer.erb

Updated YouTube Link

---

source/Guides/misc.htm.erb
source/contact.htm.erb
source/layouts/partials/_acquire_details.erb

Yet another attempt at this pull!
Hopefully I did it correctly this time. :)

Updated a bunch of URLs.

---

source/Guides/acquire-grc.htm.erb
source/Guides/boinc-install.htm.erb
source/Guides/earn-grc.htm.erb
source/Guides/gridcoin-install.htm.erb
source/Guides/investor-acquire-grc.htm.erb
source/Guides/investor-earn-grc.htm.erb
source/Guides/investor-gridcoin-setup.htm.erb
source/Guides/pool-gridcoin-install.htm.erb
source/Guides/pool.htm.erb
source/index.htm.erb
source/layouts/partials/_footer.erb

Footer, guide buttons & download link fixes
Addresses: https://github.com/gridcoin-community/Gridcoin-Site/issues/81

Updated responsiveness

---

source/Guides/boinc-install.htm.erb
source/assets/css/gridcoin.css
source/exchange.htm.erb
source/layouts/partials/_acquire_details.erb
source/layouts/partials/_boinc_1A.erb
source/layouts/partials/_solo_boinc_intro.erb

PR to solve issue #154 
* Added the suggested text by @jamescowens 
* Rearranged some text and removed redundant test,
* Fixed and linked to exchange.htm as a singular way to find exchanges without pointing to other guide pages which could confuse users.
* Removed a unavailable YouTube video guide while I was at it.
*Added a new partial to prevent these changes also affecting the pool guide where most of this info is unnecessary
Review away~~~~~~

State the estimated required balance to stake - Issue #154

---

source/layouts/layout.erb
source/layouts/partials/_footer.erb

Added 100% height to html  and body tags, d-flex and flex-column'd body, keeps layout the same but streatches the footer background to fill any remaining space.

Issue#17 - Fix height issue on low content pages.

---

Guides/security.htm

Remove paper wallet link

---

CNAME

This tell github the domain we are using.
Committing this file is the same as going to the settings tab and configuring it from there.

Create CNAME file for gridcoin.us domain

---

Gemfile
README.md

Move to using page-gems to stay in sync with github gem versions.
This fixes #189

Use Page-gems to stay in sync with github gems

---

README.md
_config.yml

Change to plugins as gems is depreciated.
Update readme.md with better update instruction cause the actually update method don't work for mystical reasons.

Change config and readme.md

---

blog.htm

Fix broken blog link from original Jekyll migration

---

_includes/_footer.htm
_includes/_header.htm

Update the Gridcoin China QQ Group link with better translations as discussed in #211 
Also added a fix for #203 commented out as it will want re-adding eventually.
Fixes #211

Update GridcoinQQ links with better translation, Comment out GridcoinBasicInfo Reddit link

---

_includes/_footer.htm
_includes/_header.htm

Update the whaleshares link if Header and Footer to https://whaleshares.io/created/gridcoin
Fixes #217

Update Whaleshares Link

---

_includes/_acquire.htm
_includes/_acquire_details.htm
_includes/_footer.htm
_includes/_header.htm
exchange.htm

Remove RUDEX from exchanges

---

_includes/_footer.htm
_includes/_header.htm

Neuralminer requested on Slack that his explorer be removed from the main site (it currently 404s) until he is able to restore the service.

Remove Neuralminer's Explorer

---

_includes/_footer.htm
_includes/_header.htm

Nuad Explorer is currently broken and developer is unresponsive via email and Slack.

Remove Nuad Explorer for time being

---

Wiki/Config-File.md

Brings in text from gridcoinresearch.conf.md in the Gridcoin-Research repo. Lists more options and give a bit more info about them

Update Config File Wiki Page

---

Wiki/index.md

Removes mentions of Proof of Work from the main wiki page and updates information about inflation

Update Main Wiki Page

---

Wiki/Testnet.md
assets/css/gridcoin.css

Creates a new page with information about testnet.  Fixes an issues where the scroll on anchor tags wouldn't be correct because of the navbar. 
Pinging @barton2526 for review of the testnet page

Create Testnet Wiki Page and Fix Anchor Scrolling

---

Wiki/FAQ.md

Most of the information is quite outdated now.
Now depends on #241

Readd FAQ Page.

---

Wiki/de/index.md
Wiki/de/konfigurationsdatei.md
_layouts/wiki-de.html

Brings in the first wiki pages translated to German (the index and config file) and makes a layout for other German wiki articles. 
Huge thanks to lucky2d for helping translate the page and the text in the layout and Nussi for translating the main index page

German Wiki Creation

---

_includes/_head.htm

Fixes a soon to be issue with samesite defaulting to lax which would break analytics

Change Google Analytics To Use samesite=none;secure

---

_data/blog.yml
blog.htm

Adds the GitHub and Reddit changelog link for 5.0.0.0
Also adds a `<br>` tag between the first and second link so they are spaced out

Blog: Add The 5.0.0.0 Release

---

contact.htm

* fixes old vulnerability process GitHub link
* fixes old slack link

Contact Page: Fix Links For Security Issue Reporting

---

_includes/_end_dropdown.htm
_includes/_start_dropdown.htm
wiki/rpc.md

Since the RPC page is so out of date, I think it might be good to push a work in progress version to the site instead of waiting for it to all be complete.

Wiki: RPC Page Update (partial)

---

_data/whitelist.yml
assets/css/gridcoin.css
guides/whitelist.htm

These are minor, but just helps make it easier to find a project on the page and clearer about the greylist monitoring website since I have seen some people get confused by it in the past

Whitelist: Update Information, Clarify, & Add Coloring To Table

---

_data/whitelist.yml
assets/css/gridcoin.css
guides/whitelist.htm

* Creates a column on if a project requires you to enable stats exports 
* each place where it is required says "required" and also links to steps on how to change the setting for that project 
* <details>
<summary>Click to see images of the columns added </summary>
On Large Display (i.e Desktop):
On Medium Sized Displays (removes the column of "Sponsor" to make it fit)
On Small Displays (i.e phones)
</details>
* Creates a header before the table
* Separates it from the graylist section 
* Also gives it an id so you can jump to it in the future with https://gridcoin.us/guides/whitelist.htm#projects
* Creates a section at the bottom that explains GDPR and also lists out the projects along with the links of the steps to enable GDPR. 
* Also gives it an id so you can jump to it in the future …

Whitelist: Add GDPR Stats Export Info

---

_includes/_footer.htm
_includes/_header.htm
assets/css/gridcoin.css
assets/img/wiki/staking_on.svg
guides/earn-grc.htm
guides/whitelist.htm
wiki/addnodes.md
wiki/boinc.md
wiki/cmd-options.md
wiki/config-file.md
wiki/gridcoin-classic.md
wiki/publications.md
wiki/staking.md
wiki/whitelist-process.md

Creates pages about:
* Publications mentioning Gridcoin (closes #240 )
* Staking
* BOINC
* Whitelist process
* Command line arguments
Update:
* Addnode page
* Config file page
Adds mentions to some of these new wiki pages across the site. Adds the page on publication mentioning Gridcoin list to the header and footer

Wiki: Create New Pages & Update Some

---

wiki/magnitude

I've included all the relevant information I could think of relating to magnitude. It would be useful if the formulae could be illustrated in a proper mathematical fashion on the webpage, as I don't believe this is possible with markdown.

Create Magnitude Page

---

assets/css/gridcoin.css
assets/img/wiki/external_link.svg
wiki/advantages-and-features.md
wiki/faq.md
wiki/foundation.md
wiki/gridcoin-classic.md
wiki/pages.md
wiki/rpc.md
wiki/staking.md
wiki/testnet.md
wiki/voting.md
wiki/whitelist-process.md

* Adds a light blue icon next to external links to differentiate them from inter-wiki and inter-site links like many wikis do
* Create a page about voting and polls
* Creates a page about the foundation

Wiki: New Pages & Add Icon For External Links

---

_layouts/wiki-sv.html
assets/css/gridcoin.css
wiki/pages.md
wiki/sv/index.md

Creates the start of a Swedish wiki with translations from @sweede-se

Wiki: Create Swedish Wiki

---

wiki/vanity.md

Please squash changes when merged.

Create wiki page about Vanity addresses.

---

wiki/de/index.md
wiki/index.md
wiki/sv/index.md

Add new faucet on Gridcoinstats

---

index.htm

Adds a tooltip that says "Whether running a wallet in these modes helps increase decentralization", This probably can be made better, but it was difficulty to think of anything concise that clarified a bit more than this. Open to any other suggestions
Closes #34

Home Page: Explain What "Secures Network" Means

---

README.md

Add info about workarounds required on WSL

---

libera.chat

This reverts commit b3d0b32536b1dc837ab9ba4b5a8d8ca701d43045.

Revert "Proof of ownership for libera.chat  (#306)"

---

wiki/rpc.md

The neuralhash and myneuralhash Rpc Commands are old and don't exist anymore

Remove old removed Rpc Commands

---

Gemfile

Ref: https://github.com/jekyll/jekyll/pull/7562

Windows needs tzinfo <v2

---

_includes/_boinc_1B.htm

Remove a mention of the old team requirement that was missed in da4c54bbeff686bee1aa76c7573cac475c2fa9db
Closes #335

Guide: Update No Account Manager Steps | Remove Team Requirement Mention

---

wiki/faq.md

This solves #341 
Spellcheck has been completed. Please let me know if any wording should be changed or any additional questions should be added.

Added a FAQ section to the wiki for MRC

---

wiki/vanity.md

Changed link for vanitygen

---

_data/whitelist.yml

Both projects have been dead for at least a year.

Remove Asteroids and Minecraft from whitelist

---

README.md
_config.yml
_layouts/wiki-pt.html
wiki/pt/index.md
wiki/pt/staking.md

I ran to a problem with the build of the jekyll in my machine, so I added this solution at the readme.
https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902
I also saw that one commom issues on the site is the improvement of the wiki, so I gave a first try.
I really like this project and I hope to help as much as I can.

Added the portuguese wiki and update README

---

_includes/_acquire.htm
_includes/_header.htm
guides/earn-grc.htm
guides/pool-to-solo.htm

A first stab at a guide for people transitioning from pool to solo. Possibly still a bit scarce, I am thankful for any help / suggestions.

Add guide to move from pool to solo

---

wiki/faq.md

I ran into some problems and I thinks that this solutions should be at this FAQ to be easy to solve them.
I don't know if it is in the right place tho.

Adding more info in the faq

---

_includes/_header.htm
guides/foldingathome.htm

Create preliminary Folding@Home Guide page

Create Folding@Home Guide

---

wiki/team-and-contributors.md

Fix typo on contributor page

---

wiki/voting.md
wiki/whitelist-process.md

Update the poll AVW requirements after the conclusion of the recent poll (https://github.com/gridcoin-community/Gridcoin-Tasks/issues/254).

Update poll AVW parameters

---

wiki/cmd-options.md
wiki/config-file.md
wiki/rpc.md

Clarify language around rpc command rpcallowip

---

_data/whitelist.yml
_includes/_acquire_details.htm
_includes/_boinc_1B.htm
_includes/_boinc_1C.htm
_includes/_solo_boinc_intro.htm
guides/earn-grc.htm
guides/foldingathome.htm
guides/noncruncher-gridcoin-setup.htm
guides/optimization.htm
guides/pool.htm
index.htm

Changes:
Whitelist:
- Update WCG sponsorship information
- Note SiDock accepts GRC donations
Pool guide:
- Add "solo is suggested method" warning to pool guide
Solo crunching guide:
- Remove references to pool in solo crunching guide
- Add branch-off for picking optimal projects
- Bold section about using same e-mail for all projects
- Remove section asking user to choose whether they want to use an account manager or not
- Add section noting account managers work with Gridcoin
- Add note about editing computing preferences
- Fix typo in earn-grc section (originally introduced by me, my bad!)
- Add troubleshooting steps for CPID mismatch error
Optimal crunching guide:
- Create this page
- Move tips for picking optimal projects into this guide
- Add some tips
Non-cruncher guide:
- Clarify …

Various edits to improve accessibility of user guides

---

_includes/_acquire.htm
_includes/_boinc_1B.htm
_includes/_header.htm
_includes/_solo_boinc_intro.htm
_includes/_wallet_install.htm
contact.htm
guides/earn-grc.htm
guides/gridcoin-install.htm
guides/whitelist.htm
index.htm
wiki/advantages-and-features.md
wiki/beacons.md
wiki/faq.md
wiki/scraper.md
wiki/staking.md

Firstly, my apologies I thought I made this into a different branch but when I did a `git push` it just put it in master. Please let me know your feedback and suggestions on these edits, I expect some of them would benefit from some further thought/discussion.
Index page:
Fix capitalization to match rest on "participate" on index page
Add option to use Gridcoin
Add tooltip explaining voting
Clarify staking rewards tooltip
Whitelist page:
Add tooltip to GPU noting availability of WUs
Menu:
Put discord to top of chat menu since it seems to be the most widely used one
Contact:
Put discord to top of chat list since it seems to be the most widely used one
Advantages and features:
Expand on federated oracle system, note that consensus is seperate from scraping
Removed comparison to Primecoin …

Various edits to site to update documentation

---

guides/earn-grc.htm

Users keep missing this, Jim sent me a ping on discord the other day saying this needs to be more obvious.

Add note about CPID issues

---

_includes/_footer.htm
_includes/_header.htm

Add a lemmy link to the menu due to Reddit exodus

Add Lemmy link to menu

---

exchange.htm

Add sciencestats to faucet list

Add sciencestats to faucet list

---

guides/whitelist.htm

Add GPU badges to whitelist on mobile

Add GPU badges to whitelist on mobile

---

wiki/faq.md

Make MRC fee portion more readable, provide examples

Clarify how MRC works in FAQ

---

_includes/_solo_boinc_intro.htm

We seem to have a number of users recently who have been confused as to why their scienceunited client isn't working with Gridcoin. This adds a warning to the solo crunching guide about that,

Add note warning about scienceunited

---

guides/whitelist.htm

And provide instructions on how to find it in the wallet

Make it clear that wallet is best source of greylist information

---

guides/earn-grc.htm

Fix sidestake instructions

---

guides/noncruncher-earn-grc.htm

Clarify how staking works and link to the appropriate wiki entry. Previous language made it sound like you had to do something special ("unlock wallet for staking") to stake, but this is no longer the default configuration.

Clarify how staking works

---

_data/whitelist.yml

As they have recently added AMD support to their project https://asteroidsathome.net/boinc/forum_thread.php?id=967

Add AMD support for asteroids in whitelist

---

wiki/whitelist-process.md

Sorry these keep slipping through

fix small typo

---

guides/earn-grc.htm

Update earn-grc.htm to make units in GRC

---

_data/exchanges.yml

This reverts commit 6293ed91108ad4a94a655d7b883f35d4bbc9cf56.

Revert "Remove SafeTrade"

---

_data/whitelist.yml
assets/css/gridcoin.css
guides/whitelist.htm

Add greylist flag, also improves default colours for whitelist page for people who see worse dark colours

Add greylist flag to each project and display so

---

wiki/faq.md

This was pointed out on Discord

Remove deleted youtube video

---

_data/whitelist.yml
wiki/whitelist-process.md

Universe@Home is dead.
https://universeathome.pl/universe/forum_thread.php?id=754

Remove Universe. ODLK is no longer greylisted

---

_data/whitelist.yml

They should be back in a month.

WCG is greylisted

---

_data/whitelist.yml

Minecraft is NVIDIA
