source/Guides/3rdpartyapps.htm.erb, source/Guides/terminology.htm.erb, source/index.htm.erb, source/layouts/partials/_header.erb
Brief descriptions, more detailed descriptions are in the commits.
1. Updated the downloads section so that it's a little easier to understand
2. Removed link to Moises Gridcoin Apps in wiki
3. Removed the table row containing "Gridcoin Republic" in the GRC Wiki
4. Grammar: replaced "nor" with "or" on the 3rd Party Apps page.
=> Updated downloads section, Remove link to Moises Gridcoin Apps, Remove Gridcoin Republic, Fixed Grammar Issue

source/contact.htm.erb, source/layouts/partials/_footer.erb, source/layouts/partials/_header.erb
Slack links didn't match between header and footer. Set both to the same link, which is a non-expiring Slack invite.
=> Fixed Slack Links

source/Guides/investor-gridcoin-setup.htm.erb, source/Guides/pool-gridcoin-install.htm.erb, source/layouts/partials/_acquire.erb, source/layouts/partials/_acquire_details.erb, source/layouts/partials/_footer.erb, source/layouts/partials/_header.erb
OpenLedger has failed multiple times to communicate why their Gridcoin ([open.grc](http://open-explorer.io/#/assets/open.grc)) gateway has remained offline for several months longer than necessary & they have recently [lost control of their domains to a hacker](https://steemit.com/bitshares/@mtopenledger/openledger-dex-discloses-eos-and-eosdac-mainnet-token-swap-details) :face_with_head_bandage:
=> Temporarily removing Bitshares references

source/assets/css/now-ui-kit.css
This color makes the links easier to read.
Old:
New:
=> Change link color

source/layouts/partials/_footer.erb
Temp change until new permanent custom URL kicks in. Old custom URL is no longer valid.
=> Update YT URL.

source/layouts/partials/_footer.erb, source/layouts/partials/_header.erb
Adds the Gridcoin QQ chatroom to the community section in header and footer.
Issue: #147
=> Added chinese QQ group to footer & header

source/layouts/partials/_footer.erb
We managed to miss this in the original PR so here's a quick fix.
=> Fixed link having a class it shouldnt have.

source/contact.htm.erb
This should fix #167 , need someone to check that I didn't miss some other mention of Discord on the site
=> Change Gridcoin Discord link to invite

_config.yml
This enable sitemap auto generation on build.
The repository tag enables local github meta data which will get rid of 'no repo' error when building locally.
We use 'gems' cause github uses version 3.1.6
also excluded CNAME on the build.
=> Add sitemap auto generation.

_data/whitelist.yml
Universe@home's https certificate isn't valid for the www subdomain, making www.universeathome.pl/universe show a certificate error when shown. https://universeathome.pl/universe/ without the www subdomain doesn't show the error
=> Fix Universe@home Link

robots.txt
Added a sitemap link and fixes some formatting. A sitemap link being in the robots.txt is recommended practice. Isn't strictly necessary but won't hurt to have.
=> Formatting and Added a Sitemap to robots.txt

assets/css/now-ui-kit.css
'font-display: swap' makes sure the text is shown before the fonts are loaded.
https://css-tricks.com/font-display-masses/
=> add font-display: swap;

_includes/_wallet_install.htm, _layouts/layout.htm, assets/js/fetch-release.js, index.htm, source/assets/js/fetch-release.js
Clean PR for the dynamic version number.
Right now it's purely the version number that updates. If #174 is merged I could expand this to automatically update download links based on assets available on Github.
Depends if we are moving 100% to hosting all download assets on github.
Would require labelling each asset to make it easier to filter them.
=> Issue#79 - Dynamic version number

Dev/rpc-reference.htm, Guides/acquire-grc.htm, Guides/boinc-install.htm, Guides/earn-grc.htm, Guides/gridcoin-install.htm, Guides/investor-acquire-grc.htm, Guides/investor-earn-grc.htm, Guides/investor-gridcoin-setup.htm, Guides/misc.htm, Guides/pool-gridcoin-install.htm, Guides/pool.htm, _includes/_acquire.htm, _includes/_acquire_details.htm, _includes/_boinc_1A.htm, _includes/_boinc_1B.htm, _includes/_boinc_1C.htm, _includes/_footer.htm, _includes/_solo_boinc_intro.htm, _includes/_wallet_install.htm, _layouts/layout.htm, assets/css/gridcoin.css, blog.htm, contact.htm, exchange.htm
Updating the bootstrap classes from their V3 versions to V4 fixes the issue with IE11.
I've also added better fix for the 100% height issue on low content pages as suggested by cycy.
=> Update bootstrap classes from V3 to v4 - Fixes IE11 issues

_includes/_footer.htm, _includes/_header.htm
Added Core Wallet Contributors link to both nav menu and footer under development section
Added a General Repo Link to nav menu under development section.
This follows a discussion on slack about the lack of a team page and such.
This is a start in providing more resources related to the development of gridcoin.
=> Add contributors link, general repo link

_includes/_footer.htm, _includes/_header.htm
Was added in #88 but now the server is down permanently as far as I know. I also used git grep to check that a link to rocket chat wasn't anywhere else only found it in the footer and header.
=> Remove Rocket Chat From Footer and Header 

_includes/_acquire_details.htm, _includes/_footer.htm, _includes/_header.htm, contact.htm, exchange.htm
This is following a 4-1 vote on the web-dev Slack channel.
We have not had a Gridcoin tagged post on Whaleshares in nearly a month and we are not seeing any real interaction with the userbase.
This change can be easily reverted if the platform sees more activity in the future.
=> Remove references to Whaleshares, Fix Slack invite

_includes/_solo_boinc_intro.htm
Moves the 5k GRC recommendation up to the top of the solo guide in bold. Also adds a header reading "IMPORTANT NOTICE".
=> Make 5k GRC Recommendation More Visable

Wiki/index.md
https://grcexplorer.neuralminer.io/ has been down for a long time now. I removed it and instead added https://gridcoin.network/
=> Remove Gridcoin.neuralminer and add gridcoin.network

_layouts/wiki.html, assets/css/gridcoin.css, assets/js/details-element-polyfill.js
Adds a drop down linking to other wiki pages that's generated dynamically. Also fixes up styling issues caused by a typo. Removes unneeded version fetching JS in wiki pages. Adds a JS polyfill (under MIT even though it doesn't say that at the top of the file) since `<details>` elements don't work on internet explorer. 
This is mostly just to separate some of the stuff of from the RPC page overhaul
=> Add Other Wiki Pages Menu & Minor Cleanup

Wiki/Config-File.md
Adds some line breaks to make things cleaner and add \ escapes to stop things getting converted to HTML tags
=> Config-File Wiki Add Spacing & Escapes

Wiki/de/index.md
This fixes an issue in #244 with a sentence that's cutoff. I believe this conflicts with #246 so I will need to rebase that pull request after this is merged
=> Fix Cutoff Sentence In German Wiki

wiki/de/index.md
Makes it so that `gridcoin.us/Wiki/de/`redirects since currently only `gridcoin.us/Wiki/de` redirects. Search engines were using the trailing slash at the end so this does actually break that link. Otherwise I wasn't able to find any links that were broken
=> Fix German Wiki Index Page Redirect

assets/css/gridcoin.css
Increases contrast by making the links brighter to make the links more readable. 
This makes the links meet WCAG accessibility standards for contrast ratio. The links now have a ratio of `5.37 : 1` compared to the previous `2.71 : 1`. The minimum contrast ratio to meet the standards for text is `4.5 : 1`
Additionally, for me these links are now way more readable
=> Make Link Color Brighter

_includes/_footer.htm, _includes/_header.htm, assets/css/gridcoin.css, wiki/faq.md
Changes the links in the header and footer to go to the new /wiki/faq.html instead of wiki.gridcoin.us/FAQ which just redirects to the github wiki (not even the FAQ page) where the wiki page there is out of date. 
Updates the formatting to make the long headers smaller and put horizontal rules between each question to better separate them. Also fixes a missed newline to make the markdown table on the faq page work.  It also updates the bluepaper link to be on site and adds a missing period
=> Update FAQ Formating And Links

assets/js/fetch-release.js, index.htm
Doesn't show direct links if they are missing from the assets from GitHub or loading and waiting for GitHub's response. 
Linux ones could be added in the future.
Currently hosting this on my fork at https://roboticmind.github.io
=> Main Page: Add Direct Download Links For Windows

_includes/_footer.htm, _includes/_header.htm
Adds them in the publications section where the whitepaper is linked
=> Add Bluepaper Links To Header & Footer

_includes/_footer.htm, _includes/_header.htm, guides/investor-gridcoin-setup.htm, guides/pool-gridcoin-install.htm, wiki/de/index.md, wiki/index.md
Since Coinomi no longer supports Gridcoin, the links to it should be removed from the site. 
This should hopefully cover all the links. I have searched with my IDE and with `git grep` and these were all the links that I found.
=> Remove Links To Coinomi

wiki/index.md, wiki/pages.md
Creates a page that lists all wiki pages in all languages. This helps link people to a list of existing pages without having to explain about the sidebar and lets people see the list in all languages
Also clarifies the index page title to be `Gridcoin Wiki Home` so it's more clear than `Gridcoin Wiki` on the sidebar and the page list page 
Looks like this:
=> Wiki: Create Page List Page

_data/whitelist.yml
I mistakenly put in #279 that Minecraft@Home has CPU tasks, but it does not. Fixes that here
=> Whitelist: Correct That Minecraft@Home Doesn't Have CPU Tasks

_includes/_acquire.htm, _includes/_footer.htm, _includes/_header.htm, guides/pool-gridcoin-install.htm, wiki/faq.md
* Update the links of the snapshot to the new one with CDN (snapshot.gridcoin.us/snapshot.zip) 
* Update all the mentions about how to use the snapshot to mention the built in download tool
=> General: Update Snapshot Link & Instruction

_includes/_footer.htm, _includes/_header.htm, contact.htm, guides/whitelist.htm, wiki/de/index.md, wiki/faq.md, wiki/foundation.md, wiki/gridcoin-classic.md, wiki/index.md, wiki/staking.md
Their site has been broken for about a month now and keeps redirecting to google for every page.
* Removes references of it as a community site
* Replaces some links with archive.org links where needed and available
=> General: Remove Cryptocurrencytalk Links

_includes/_footer.htm, _includes/_header.htm, wiki/de/index.md, wiki/index.md
* Adds Gridcoin.ch as a block explorer in the header and footer of the page as well as wiki links
* Remove some commented out dead links that have been offline for quite some time
=> Links: Add Gridcoin.ch As Block Explorer

guides/noncruncher-gridcoin-setup.htm
Correct a typo to make the link at the bottom of the Gridcoin-Setup page not give a 404. Is only a minor issue since this is linking to the page it's are already on. Checked for other typos of this link and didn't find any more
=> Minor: Fix Link at Bottom of Gridcoin-Setup Page

_data/whitelist.yml
Now that World Community Grid Has GPU work (see [here](https://www.worldcommunitygrid.org/about_us/viewNewsArticle.do?articleId=693)), we should update it on the whitelist page to reflect that
=> Whitelist: Update WCG to Mention New GPU Work

wiki/voting.md
Adds a clarification about how abstentions are not counted in terms of a poll's yes/no ratio. Was something that was missed in #278
=> Wiki: Clarify How Abstentions Are Excluded

_data/whitelist.yml
Since the poll has now passed & been validated, SIDock@Home is now on the whitelist!
Note that the Gridcoinstats,eu stats URL doesn't work yet, but putting in by looking at how the names for other project have been put in place in the pas (i.e all lowercase and with the @ in the URL). Can update if needed, but I think that link is not as important as having the project listed on the site
=> Add SiDock@Home to Whitelist

wiki/de/index.md, wiki/index.md, wiki/sv/index.md
Wiki home pages in all languages used a broken discord.me link for some reason. Switched them to use the same link that's in the header and footer
=> Wiki: Fix Discord Links 

wiki/addnodes.md
Requested by @wilkart, Closes gridcoin-community/Gridcoin-Wiki#6
DNS Load balancer for all of the replaced servers.
Additionally:
* Removed dead servers from list
* Update status from addnodes.cycy.me
=> Replace all *.gridcoin.pl with seed.gridcoin.pl

wiki/faq.md
Moved the text to the end of the line where it won't be interpreted as a numbering (only works at start of a line). I think that this is the simplest to read fix to this
**New:**
**Old:**
=> Wiki: Fix 2003 Being Interpreted as Numbering

wiki/utxos.md
Fixes an error on the UTXO page that @jamescowens mentioned about Gridcoin using coin*stakes* and not coinbases
=> Wiki: Fix Incorrect Usage of Coinbase

_data/whitelist.yml
LHC and YAFU will likely be greylisted for the foreseeable future.
https://twitter.com/GridcoinNetwork/status/1385239153630236676
=> Remove LHC and YAFU from whitelist

wiki/foundation.md
A bad address should not be in the same document people visit to donate
=> Remove unused address to avoid confusion.

wiki/scraper.md, wiki/superblock.md
While I'm reading the Superblock wiki, I tried to click the scrapers link, which is currently 404 not found. This PR fixes the typo link from `scrapers` to `scraper`
Also, I found that the 1st paragraph of the Scraper wiki can be improved by adding links so it's clickable 😉
=> Fix typo link in Superblock doc and add link in the Scraper doc

_includes/_create_card.htm, _includes/_end_row.htm, _includes/_footer.htm, _includes/_header.htm, _includes/_start_row.htm, wiki/team-and-contributors.md
Creates a team and contributor page organized by role. Each user listed has a card with their GitHub profile picture and a brief description of their role . 
Can look at it running on my fork at https://roboticmind.github.io/wiki/team-and-contributors.html
=> Create Team and Contributors Page

wiki/advantages-and-features.md, wiki/de/index.md, wiki/de/konfigurationsdatei.md, wiki/index.md, wiki/sv/index.md
* Fixes two wiki links that are incorrectly capitalized
* Update the home wiki page TODOs about a `Volunteers,-Roles,-&-Privileges` page  
* For the en wiki use the new `team-and-contributors` page
* For the other languages, update the TODO comment to match the new page name
=> Wiki, Minor: Fix Capitzliation Issues and Update TODOs

assets/js/fetch-release.js, index.htm
* Add macOS builds to the downloads 
* Fetch old versions if any platform doesn't yet have a build
*  Has a warning at the bottom for each platform with an old build
Screenshot of what this currently looks like 
Screenshot of what this would look like when fetching old versions
<sup>Note that there has been some capitalization changes since I took these screenshots</sup>
Closes #338
=> Update Fetch Release Script and Index Page

wiki/beacons.md, wiki/faq.md, wiki/scraper.md
* Updates the scraper page which was previously written before the scraper system went into place
* Creates a short page about beacons
* Remove more mentions of the team requirement (since I seem to keep missing some no matter which search terms I use...)
=> Wiki: Scraper Page Update, New Beacon Page, and Remove More Mentions of the Team Requirement

wiki/rpc.md
Adds the missing `revokebeacon` command to the rpc wiki page.
=> add `revokebeacon` command

wiki/scraper.md
The correct command is `listmanifests` and not `listmanifest`.
=> fix typo `listmanifests` command

_data/whitelist.yml
- Asteroids is back
- Collatz and Cosmology have been dead for a while
- SiDock comes before SRBase
=> Add Asteroids to the whitelist. Remove Collatz and Cosmology. Fix order

.github/workflows/ci.yaml
This fixes intermittent CI failures because node 12 is deprecated.
=> Use checkout v3

wiki/faq.md
Rewrite this FAQ entry. I think this says the same things but more clearly answers the question and provides users with a suggested setup instead of saying "don't do these things, now figure out how to connect your devices without breaking these rules".
=> Rewrite language on multiple machines FAQ to make things clearer

_includes/_acquire.htm, _includes/_footer.htm
Snapshots are being disabled and don't work at this point due to the snapshot hosting site being down.
=> Remove references to snapshot from footer and solo crunching guide

guides/earn-grc.htm
Making this PR in response to some users who have come in confused about these things recently.
1. Solo crunching guide now mentions that the project they change their username on must not be greylisted. Users were changing their name at greylisted projects and being confused as to why their beacons did not activate.
2. It also mentions how rewards work and how to claim them.
=> Add information about greylist, rewards

index.htm
I propose changing the title text of the main page from "Rewarding Volunteer Distibuted Computing" with "The Cryptocurrency of Science". My rationale is as follows:
- We should have our branding be clear and make a concise, easy-to-understand pitch to the visiting user. Our main pitch is that we are a cryptocurrency that supports science. "The Cryptocurrency of Science" says this quite concisely.
- "Rewarding Volunteer Distributed Computing" is a mouthful and uses scary technical language that will not seem accessible to average computer users. Even users experienced with cryptocurrency mining may not know what "volunteer computing" or "distributed computing" is. 
- A user who is interested in Gridcoin merely as a cryptocurrency and has no interest in crunching probably doesn't need to …
=> Replace "Rewarding Volunteer Distributed Computing" with "The Cryptocurrency of Science"

README.md
Clearer instructions for new users on how to contribute to the Gridcoin site if they are not familiar with Git
=> Make readme easier for new users

README.md
=> remove errant 7

README.md, guides/whitelist.htm
Some updates to make whitelist guide more readable
- Move whitelist process & history info to bottom of page. People are coming here to see the whitelist, not get a history lesson :p. This makes the actual whitelist content now appear "above the fold"
- Add hover text for GDPR column
- Clarify how to find whitelist info in wallet
- Eliminate a few un-necessary words to reduce word count
=> Whitelist updates

wiki/testnet.md
Would it be worth linking directly to the testnet channel? (https://discord.com/channels/211637812968161280/1153591383811174430)
=> Change all instances of Slack to Discord

wiki/faq.md
Add instructions for:
- Fixing wallet with corrupt DB
- Migrating wallet between machines
=> Wallet reset

_data/exchanges.yml
The website has been down for several days already according to a user on Discord. We can add it back once it is online again.
=> Remove SafeTrade

.github/workflows/ci.yaml
Ruby 3.0 goes EOL in March. This will give us until 2025.
Tested and I see no changes on my branch.
=> Bump Ruby to 3.1

guides/gridcoin-install.htm, wiki/testnet.md
This is not used in the Gridcoin wallet and has not been for some time now.
=> Remove references to boincappdir

wiki/whitelist-process.md
For some reason I wrote the term median earlier when the definition has always used the mean
The original definition was defined as
> WAS = Green If (**Mean** daily credit for 7 Days > (0.1 * **Mean** daily credit for 40 Days)) Else Red
https://github.com/gridcoin-community/Gridcoin-Tasks/issues/194
(Dividing the two gives you the same form as it exists on the site of
Mean daily credit for 7 Days / Mean daily credit for 40 Days > 0.1)
=> Minor: Correct the term median to mean in the whitelist process

exchange.htm
The faucet appears to be serving malware. Remove it from the list.
=> Remove ScienceStats faucet
